name: Sync Fork

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 06:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/n8n-io/n8n-docs.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories || echo "No changes to merge"

    - name: Push changes
      run: git push origin main
